name: test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
        name: test build
        run: docker build -t 4s3ti/rstudio-server:latest .